Yakov/read file hook
datarobot/datarobot-user-models pull request #131
Opened 2020-09-05 01:06 UTC by yakov-g

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary

## Rationale

2020-09-05 04:52 UTC, yakov-g commented
jarvis test functional_drop_in

2020-09-08 18:31 UTC, meltzg requested changes
update env ids?

2020-09-08 18:56 UTC, yakov-g commented on README.md
> +  - If used, this hook must return a non-None value
done

2020-09-08 19:05 UTC, yakov-g commented on README.md
> +- `read_file(input_filename: str) -> Any`
yes, sounds better.
fixed

2020-09-08 19:18 UTC, 4dahalibut commented
can you name it read_data or read_csv

2020-09-08 19:24 UTC, meltzg approved these changes

2020-09-08 19:28 UTC, yakov-g commented
> can you name it read_data or read_csv
It can not be `read_csv` as in wild model input can be anything.

@meltzg @4dahalibut So either `read_input` or `read_data` ?

`read_input` is very clear but not very nice...
`read_data` is nicer but less clear

2020-09-08 19:29 UTC, 4dahalibut commented
read_input_data then maybe.

2020-09-08 19:39 UTC, meltzg commented
i like `read_input` because it matches the `--input` flag

2020-09-08 19:46 UTC, yakov-g commented
I'd also choose `read_input_data`.
Do we want to ask on linguists forum?

2020-09-08 19:49 UTC, yakov-g commented
Let's do `read_input_data`
there is some `read_input` method in R https://www.rdocumentation.org/packages/pastis/versions/0.1-2/topics/read_input

And we also, might need to rename `init` as I saw some warning that it clashes with R init

2020-09-08 19:51 UTC, yakov-g commented
We may also add `drcm` prefix to the hooks to avoid clashing.

2020-09-08 20:05 UTC, 4dahalibut approved these changes

2020-09-08 21:44 UTC, merged

2020-09-08 21:44 UTC, datarobot-jarvis commented
:dollar: Total cost of executing tests in Jenkins: $**9.18** USD.

[What is this all about?](http://bit.ly/2BahK4V)