[RAPTOR-3742] Add score for multiclass
datarobot/datarobot-user-models pull request #166
Opened 2020-10-16 23:47 UTC by meltzg

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary

## Rationale

2020-10-18 04:32 UTC, yakov-g commented
jarvis test functional_drop_in

2020-10-18 06:33 UTC, yakov-g commented
your test functional tests fail because of this:
https://github.com/datarobot/datarobot-user-models/pull/167

2020-10-19 15:54 UTC, meltzg commented
jarvis test cmrunner_integration

2020-10-19 16:07 UTC, meltzg commented
jarvis test cmrunner_integration

2020-10-19 17:11 UTC, yakov-g commented
jarvis test cmrunner_integration

2020-10-19 17:11 UTC, yakov-g commented
jarvis test functional_drop_in

2020-10-19 17:47 UTC, meltzg commented
this PR also contains the fix for https://datarobot.atlassian.net/browse/RAPTOR-3766

2020-10-19 22:02 UTC, meltzg commented
jarvis test functional_drop_in

2020-10-20 00:05 UTC, meltzg commented
jarvis test functional_drop_in

2020-10-20 08:00 UTC, yakov-g commented
jarvis test functional_drop_in

2020-10-20 10:58 UTC, rvorobii approved these changes
looks good

why are binary classification models updates (e.g. tests/fixtures/drop_in_model_artifacts/iris_bin.pmml)?

2020-10-20 10:58 UTC, rvorobii commented on custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/custom/ScoringCode.java
> +                var labelsArr = this.classLabels.toArray(new String[this.classLabels.size()]);
nit: maybe we could use `String[]` instead of `List<String>` for `classLabels`, so that there's no `toArray` conversion.

2020-10-20 14:47 UTC, meltzg commented
@rvorobii for most of the fixtures that got remade, it was just due to me re-running the entire notebooks that make them.  For the binary PMML model, the model needed to be replaced because the model was actually a multiclass model hand modified to look like it was binary.

2020-10-20 16:47 UTC, yakov-g commented on tests/conftest.py
> +    (None, MULTICLASS): os.path.join(TESTS_DATA_PATH, "Skyserver_SQL2_27_2018 6_51_39 PM.csv"),
Please remove spaces in the filename.
And I'd even lowercase it.

2020-10-20 16:49 UTC, yakov-g commented on tests/drum/test_inference.py
> +        cmd = '{} score --code-dir {} --input "{}" --output {} --target-type {}'.format(
Ohhh, that's because if whitespaces in the filename

2020-10-20 16:53 UTC, yakov-g requested changes
So do you mind removing those whitespaces?

2020-10-20 17:35 UTC, yakov-g approved these changes

2020-10-20 19:30 UTC, merged

2020-10-20 19:30 UTC, datarobot-jarvis commented
:dollar: Total cost of executing tests in Jenkins: $**14.04** USD.

[What is this all about?](http://bit.ly/2BahK4V)