[RAPTOR-5568] Show R Traceback for fit/predict errors
datarobot/datarobot-user-models pull request #357
Opened 2021-06-11 18:40 UTC by jmbannon

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Previously, R errors only showed a single-line error message. This PR will run traceback() when an R runtime error occurs to print the full traceback.

![Screenshot from 2021-06-11 11-14-48](https://user-images.githubusercontent.com/10107080/121734555-c945a300-caa9-11eb-8148-ff3f383dfcd6.png)

2021-06-11 19:21 UTC, meltzg requested changes
test?

2021-06-11 21:24 UTC, jmbannon commented
@meltzg test has been added

2021-06-12 00:22 UTC, yakov-g approved these changes

2021-06-12 04:09 UTC, meltzg approved these changes

2021-06-14 20:20 UTC, merged