[RAPTOR-5540] support all datatypes
datarobot/datarobot-user-models pull request #373
Opened 2021-06-30 15:30 UTC by scottp-ml

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
This is to match the validation used in DR for the schema.  NO runtime validation in DRUM is supported for some types, such as audio, at this time. 

## Rationale

2021-07-04 16:16 UTC, 4dahalibut commented on custom_model_runner/datarobot_drum/drum/typeschema_validation.py
> +                "Values specified do not have runtime validation in DRUM, only within DataRobot."
can you add the specific value in this info message.

2021-07-04 16:16 UTC, 4dahalibut approved these changes
LGTM but please make single change.

2021-07-04 16:17 UTC, 4dahalibut commented
Have you manually tested using these data types w datarobot yet?

2021-07-06 12:36 UTC, scottp-ml commented
I have not built a task for each one.

2021-07-06 17:19 UTC, eric-s-s commented on VALIDATION-SCHEMA.md
> +- IN: The types are supported, but not all are required to be present.
All of the listed data types are supported  (mirroring the equals language)

2021-07-06 17:30 UTC, eric-s-s requested changes
somewhere around: `tests.drum.unit.test_typeschema_validation.TestSchemaValidator.test_data_types` , please write test for the following cases:

- Values.DATE_DURATION
- all operators with each of the types we don't validate
- all operators that take multiple types with 
  - 2 types we don't validate
  - a type we do validate and a type we don't

2021-07-15 20:03 UTC, eric-s-s approved these changes
:+1: looks good!

2021-07-22 16:26 UTC, merged