[RAPTOR-5822] add schema for remaining templates
datarobot/datarobot-user-models pull request #400
Opened 2021-08-13 18:54 UTC by scottp-ml

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Part 2.  Add typeschema to tasks and estimator templates.  

## Rationale

2021-08-18 17:56 UTC, jmbannon commented on task_templates/estimators/python_anomaly/model-metadata.yaml
> +  input: ../../../tests/testdata/boston_housing.csv
doesn't this have text? We should make sure these validation ones work

2021-08-18 17:57 UTC, jmbannon commented on task_templates/estimators/r_binary_classification/model-metadata.yaml
> +environmentID: 5e8c889607389fe0f466c72d
this needs to match the recent R public env ID

2021-08-18 17:57 UTC, jmbannon commented on task_templates/estimators/r_regression/model-metadata.yaml
> +environmentID: 5e8c889607389fe0f466c72d
R env id

2021-08-18 17:58 UTC, jmbannon requested changes
Lets set the validation input to whatever the functional test uses for each template. And make sure R uses the R env ID

2021-08-18 18:03 UTC, scottp-ml commented
@jmbannon The issue with setting them to accept the input of the functional tests is that these were written to ignore columns that aren't useful.  So if you add text to them, that means they would be expected to work if they only received text, which isn't true.

2021-08-23 18:34 UTC, MikhailYakubovskiy commented on task_templates/transforms/custom_class_python/model-metadata.yaml
> +  output_requirements:
Scott, we should also add that this task never outputs missing values

2021-08-24 18:46 UTC, jmbannon commented on task_templates/estimators/r_binary_classification/model-metadata.yaml
> +environmentID: 610305345da4263681a176b5
On staging the R environmentID is `5ea850ca1d41c8173c2feef6`

2021-08-24 18:46 UTC, jmbannon commented on task_templates/estimators/r_binary_classification/model-metadata.yaml
> +environmentID: 610305345da4263681a176b5
https://staging.datarobot.com/model-registry/custom-environments/5ea850ca1d41c8173c2feef6

2021-08-30 19:16 UTC, merged