[RAPTOR-5841][RAPTOR-5842] R: Fix sparse input data
datarobot/datarobot-user-models pull request #416
Opened 2021-08-30 23:37 UTC by jmbannon

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Sparse support in R never really existed - it would ignore the colnames and always cast the data to dense. This PR ensures the matrix stays sparse, and passes the column names file to it.

In addition, an R bug is fixed which sampled X and y differently

## Rationale

2021-09-02 13:30 UTC, scottp-ml requested changes
Can you please add a model_metadata with typeschema for the new example?

2021-09-02 21:16 UTC, jmbannon commented on custom_model_runner/datarobot_drum/resource/components/Python/r_fit/fit.R
> +        na_rows <- rep(FALSE, nrow(X))  # Set all of na_rows to FALSE since no y values are NA
Add print if NA rows are dropped

2021-09-02 21:18 UTC, jmbannon commented on tests/fixtures/r_estimator_sparse.R
> +   data.frame('Predictions'=rep(42, nrow(X)))
add spare + colname check in score

2021-09-02 21:19 UTC, 4dahalibut commented on tests/drum/test_fit.py
> +            # This is testing an R custom task, but we have to set is_training to False because that's how you convert
cursed

2021-09-02 21:21 UTC, 4dahalibut reviewed
please add tests into predict hook for R test.

2021-09-03 20:24 UTC, jmbannon commented on tests/fixtures/r_estimator_sparse.R
> +   data.frame('Predictions'=rep(42, nrow(X)))
we don't actually pass sparse colnames to the score hook (including python).
Made a ticket: https://datarobot.atlassian.net/browse/RAPTOR-6231

2021-09-03 20:29 UTC, jmbannon commented
@4dahalibut @scottp-ml Added your comments. Ran into more issues along the way so please review the latest commit

2021-09-03 20:44 UTC, scottp-ml approved these changes

2021-09-03 22:21 UTC, jmbannon commented
jarvis test functional_inference_model_templates functional_training_model_templates

2021-09-07 18:26 UTC, jmbannon commented
jarvis test functional_inference_model_templates functional_training_model_templates

2021-09-07 22:54 UTC, merged