[YOLO] Update README with the new release adding guide
datarobot/datarobot-user-models pull request #485
Opened 2021-11-05 18:50 UTC by lkanggithub

## Summary
Add a section in README.md about how to add  a new release. The content is based on the following wiki pages. I feel it would be better to document this in the repository.
https://datarobot.atlassian.net/wiki/spaces/RAPTOR/pages/1419247790/Publishing+DRUM+to+PyPi
https://datarobot.atlassian.net/wiki/spaces/RAPTOR/pages/1416691967/Install+drop-in+environments+on+staging+production

## Rationale

2021-11-05 18:52 UTC, lkanggithub commented on README.md
> +   Update the dr_requirements.txt in functional testings (e.g., `./tests/raptor_lake_templates/environments/python_base/dr_requirements.txt`) and make sure all testings pass.
Besides the testing in datarobot-user-blueprint repo, I think we should also verify the latest release with the functional testing in DataRobot repo before updating the drop-in env in Staging/Production. 
Your thought?
@4dahalibut @yakov-g

2021-11-08 14:17 UTC, 4dahalibut requested changes
Small improvements

2021-11-08 14:17 UTC, 4dahalibut commented on README.md
> +### Adding a new release
Can you make a new file called `RELEASE.md` and put this in there maybe?

2021-11-08 14:17 UTC, 4dahalibut commented on README.md
> +6. Update drop-in environments in Production (**US/EU**)
I think you should draw attention to the fact that this script has to be run twice

2021-11-08 17:35 UTC, jmbannon requested changes
I think we are giving out too much information to the public, I think you should check with security and make sure they are okay with this. If not, the branch and PR should be force deleted to remove from the git history

2021-11-18 14:07 UTC, closed without merging

2021-11-18 14:07 UTC, lkanggithub commented
Close this pr. A new page https://datarobot.atlassian.net/wiki/spaces/RAPTOR/pages/4982014178/Create+a+new+release+of+DRUM was created to document the process.