[MODEL-7887] fix whitespace handling for class labels
datarobot/datarobot-user-models pull request #567
Opened 2022-02-01 15:35 UTC by scottp-ml

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
When class labels are passed in as a parameter to the server they were not being escaped.  This caused class labels with spaces to be treated as multiple labels, which does not match the classes of the trained label.  This escapes them so that they are handled correctly.  

## Rationale

2022-02-04 02:28 UTC, RodrigoGonzalez approved these changes
LGTM. I feel like you could have used a smaller representation of that dataset, but it’s fine

2022-02-04 11:24 UTC, rvorobii requested changes

2022-02-04 11:24 UTC, rvorobii commented on tests/drum/test_fit.py
> +            # (CUSTOM_TASK_INTERFACE_XGB_REGRESSION, REGRESSION, None),
you forgot to uncomment this

2022-02-07 14:18 UTC, rvorobii approved these changes

2022-02-07 18:03 UTC, merged